stages:
  - package

default:
  image: python:3.9-slim

workflow:
  rules:
    - if: $CI_COMMIT_TAG

package:
  stage: package
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=${CI_REGISTRY_USER} python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PYPI_PROJECT_ID}/packages/pypi dist/*